<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-20T22:44:14 IST" name="FREE CRM Application Test Automation Smoke Suite" finished-at="2023-03-20T22:44:17 IST" duration-ms="3731">
    <groups>
    </groups>
    <test started-at="2023-03-20T22:44:14 IST" name="Free CRM Application Test Cases" finished-at="2023-03-20T22:44:17 IST" duration-ms="3731">
      <class name="tests.GetUsersList">
        <test-method is-config="true" signature="init()[pri:0, instance:tests.GetUsersList@10d307f1]" started-at="2023-03-20T22:44:14 IST" name="init" finished-at="2023-03-20T22:44:14 IST" duration-ms="536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="getUsersListTest()[pri:0, instance:tests.GetUsersList@10d307f1]" started-at="2023-03-20T22:44:14 IST" name="getUsersListTest" finished-at="2023-03-20T22:44:17 IST" duration-ms="2426" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUsersListTest -->
      </class> <!-- tests.GetUsersList -->
      <class name="tests.CreateUser">
        <test-method is-config="true" signature="init()[pri:0, instance:tests.CreateUser@614ca7df]" started-at="2023-03-20T22:44:17 IST" name="init" finished-at="2023-03-20T22:44:17 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="createUserTest()[pri:0, instance:tests.CreateUser@614ca7df]" started-at="2023-03-20T22:44:17 IST" name="createUserTest" finished-at="2023-03-20T22:44:17 IST" duration-ms="583" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [lp] but found [null],
expected [haxor] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [lp] but found [null],
expected [haxor] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at tests.CreateUser.createUserTest(CreateUser.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUserTest -->
      </class> <!-- tests.CreateUser -->
    </test> <!-- Free CRM Application Test Cases -->
  </suite> <!-- FREE CRM Application Test Automation Smoke Suite -->
</testng-results>
